export const DUMMY_WORKOUT = {
  push: {
    benchPress: 3,
    inclinedDumbbellBenchPress: 3,
    crossOver: 3,
    seatedDumbbellPress: 3,
    lateralRaise: 3,
    tricepsDips: 3,
    plank: 2,
  },
  pull: {
    pullUp: 3,
    seatedCableRow: 3,
    neutralGripLatPullDown: 3,
    barbellCurl: 3,
    dumbbellHammerCurl: 3,
    rearDeltRaise: 3,
    captainsChairLegRaise: 2,
  },
  legs: {
    squat: 3,
    hackSquat: 3,
    seatedLegCurl: 2,
    legExtension: 2,
    lyingLegCurl: 2,
    seatedCalfRaise: 3,
    crunch: 2,
  },
  upperBody: {
    inclinedBenchPress: 3,
    overhandBentOverRow: 3,
    dumbbellBenchPress: 2,
    tBarRow: 2,
    facePull: 2,
    lateralCableRaise: 2,
    inclineDumbbellCurl: 3,
    closeGripBenchPress: 3,
    cableCrunch: 2,
  },
  lowerBody: {
    deadlift: 3,
    lunges: 2,
    lyingLegCurl: 3,
    legExtension: 2,
    seatedLegCurl: 2,
    legPressCalfRaise: 3,
    weightedSitUp: 2,
  },
};

export const DUMMY_REST_DAYS = [4, 7];
