import { MaleSplits } from "@/types/training-splits";

export const maleSplitsRestDays = {
  fiveDaysSplit: [4, 7],
  fiveDaysSplitUpperFocused: [4, 7],
  fourDaysSplit: [4, 6, 7],
  threeDaysSplit: [2, 4, 6, 7],
};

export const maleSplits: MaleSplits = {
  fiveDaysSplit: {
    push: [
      "High Intensity Chest Exercise - 3 Series",
      "A High or moderate intensity chest exercise (focus in a different movement angle related to the first) - 3 Series",
      "A moderate or low intensity chest exercise - 3 series",
      "Shoulders - frontal movement with moderate or low intensity - 3 Series",
      "Shoulders - lateral movement - 3 series",
      "Triceps - 3 series",
      "Abs - 2 series",
    ],

    pull: [
      "High Intensity back Exercise - 3 Series",
      "A moderate or low intensity back exercise (try to focus in a different movement pattern and grip related to the first) - 3 Series",
      "A moderate or low intensity back exercise (try to focus in a different movement pattern and grip related to the already selected exercises) - 3 series",
      "Biceps - 3 series",
      "Biceps (try to mix the movement type) - 3 series",
      "Rear deltoid exercise",
      "Abs (try to mix from the previous days) - 2 series",
    ],

    legs: [
      "Squat - 3 series",
      "A high or moderate intensity quads exercise - 3 series",
      "An isolated Hamstring exercise - 2 series",
      "Leg Extension - 2 Series",
      "A different isolated hamstring exercise - 2 series",
      "Calves exercise - 3 series",
      "Abs (try to mix from the previous days) - 2 series",
    ],

    upperBody: [
      "High Intensity Chest Exercise (with a different movement angle related to the first exercise of the push day) - 3 Series",
      "High Intensity Back Exercise (with a different movement angle related to the first exercise of the pull day) - 3 Series",
      "A moderate or low intensity chest exercise - 2 series",
      "A moderate or low intensity back exercise - 2 series",
      "Deltoids Exercise - 2 Series",
      "Side Deltoid Exercise - 2 series",
      "Biceps Exercise - 3 series",
      "Triceps Exercise (with a different movement angle related to the first exercise of the push day) - 3 series",
      "Abs (try to mix from the previous days) - 2 series",
    ],

    lowerBody: [
      "Deadlift - 3 Series",
      "A moderate intensity Quads Exercise - 2 Series",
      "Lying or Seated Leg Curl - 3 Series",
      "Leg Extension - 2 Series",
      "A leg curl different from the previous one - 2 Series",
      "Calves - 3 Series",
      "Abs (try to mix from the previous days) - 2 series",
    ],
  },
  fiveDaysSplitUpperFocused: {
    pushA: [
      "High Intensity Chest Exercise - 3 Series",
      "A moderate intensity chest exercise (focus in a different movement angle related to the first) - 3 Series",
      "A moderate or low intensity chest exercise - 3 series",
      "Shoulders - frontal movement with moderate or low intensity - 3 Series",
      "Shoulders - lateral movement - 3 series",
      "Triceps - 3 series",
      "Abs - 2 series",
    ],
    pullA: [
      "High Intensity back Exercise - 3 Series",
      "A moderate or low intensity back exercise (try to focus in a different movement pattern and grip related to the first) - 3 Series",
      "A moderate or low intensity back exercise (try to focus in a different movement pattern and grip related to the already selected exercises) - 3 series",
      "Biceps - 3 series",
      "Biceps (try to mix the movement type) - 3 series",
      "Rear deltoid exercise",
      "Abs (try to mix from the previous days) - 2 series",
    ],
    legs: [
      "Squat - 3 series",
      "A high or moderate intensity quads exercise - 3 series",
      "An isolated Hamstring exercise - 3 series",
      "Leg Extension - 3 Series",
      "A different isolated hamstring exercise - 3 series",
      "Calves exercise - 3 series",
      "Abs (try to mix from the previous days) - 2 series",
    ],
    pushB: [
      "Overhead Press - 3 Series",
      "A moderate intensity chest exercise - 3 Series",
      "A moderate or low intensity chest exercise - 3 series",
      "Side Deltoid Exercise - 3 series",
      "Triceps Exercise - 3 series",
      "Triceps Exercise (with a different movement angle related to the previous exercise) - 3 series",
      "Abs (try to mix from the previous days) - 2 series",
    ],
    pullB: [
      "Deadlift - 3 Series",
      "A vertical pull back exercise - 3 Series",
      "A horizontal pull moderate or low intensity exercise - 3 Series",
      "A Biceps exercise - 2 Series",
      "A Biceps Exercise - 2 Series",
      "Rear Delt Raise - 2 Series",
      "Abs (try to mix from the previous days) - 2 series",
    ],
  },
  fourDaysSplit: {
    push: [
      "Barbell Bench Press - 3 Series",
      "A moderate intensity chest exercise (focus in a different movement angle related to the first) - 3 Series",
      "A moderate or low intensity chest exercise - 3 series",
      "Shoulders - frontal movement with moderate or low intensity - 3 Series",
      "Shoulders - lateral movement - 3 series",
      "Triceps - 3 series",
      "Abs - 2 series",
    ],
    pull: [
      "High Intensity back Exercise - 3 Series",
      "A moderate or low intensity back exercise (try to focus in a different movement pattern and grip related to the first) - 3 Series",
      "A moderate or low intensity back exercise (try to focus in a different movement pattern and grip related to the already selected exercises) - 3 series",
      "Biceps - 3 series",
      "Biceps (try to mix the movement type) - 3 series",
      "Rear deltoid exercise - 3 series",
      "Abs (try to mix from the previous days) - 2 series",
    ],
    legs: [
      "Squat - 3 series",
      "A high or moderate intensity quads exercise - 3 series",
      "An isolated Hamstring exercise - 2 series",
      "Leg Extension - 2 Series",
      "A different isolated hamstring exercise - 2 series",
      "Calves exercise - 3 series",
      "Abs (try to mix from the previous days) - 2 series",
    ],
    fullBody: [
      "Deadlift - 3 Series",
      "Moderate Intensity Chest Exercise - 3 Series",
      "A vertical pull backs exercise - 3 Series",
      "A moderate or low intensity chest exercise - 2 series",
      "Deltoids Exercise - 2 Series",
      "Side Deltoid Exercise - 2 series",
      "Biceps Exercise - 2 series",
      "Triceps Exercise (with a different movement angle related to the first exercise of the push day) - 2 series",
      "Abs (try to mix from the previous days) - 2 series",
    ],
  },
  threeDaysSplit: {
    push: [
      "High Intensity Chest Exercise - 3 Series",
      "A moderate intensity chest exercise (focus in a different movement angle related to the first) - 3 Series",
      "A moderate or low intensity chest exercise - 3 series",
      "Shoulders - frontal movement with moderate or low intensity - 3 Series",
      "Shoulders - lateral movement - 3 series",
      "Triceps - 3 series",
      "Abs - 2 series",
    ],
    pull: [
      "Deadlift - 3 Series",
      "A vertical pull back exercise - 3 Series",
      "A moderate or low intensity horizontal back exercise (focus in a different grip related to the previous exercise) - 3 series",
      "Biceps - 3 series",
      "Biceps (try to mix the movement type) - 3 series",
      "Rear deltoid exercise - 3 series",
      "Abs (try to mix from the previous days) - 2 series",
    ],
    legs: [
      "Squat - 3 series",
      "Stiff Leg Deadlift - 3 series",
      "A high or moderate intensity quads or hamstrings exercise - 3 series",
      "An isolated Hamstring exercise - 2 series",
      "Leg Extension - 2 Series",
      "A different isolated hamstring exercise - 2 series",
      "Calves exercise - 3 series",
      "Abs (try to mix from the previous days) - 2 series",
    ],
  },
};
